import js from '@eslint/js';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        chrome: 'readonly',
        CLAWD_SCHEMA_VERSION: 'readonly',
        CLAWD_DAILY_QUESTS: 'readonly',
        CLAWD_WEEKLY_CHALLENGES: 'readonly',
        CLAWD_RARITY: 'readonly',
        CLAWD_ACCESSORIES: 'readonly',
        CLAWD_MODELS: 'readonly',
        CLAWD_FACES: 'readonly',
        CLAWD_SKINS: 'readonly',
        CLAWD_ACTIONS: 'readonly',
        CLAWD_PET_EXTRA_ACTIONS: 'readonly',
        CLAWD_PROFESSIONS: 'readonly',
        CLAWD_SUBPETS: 'readonly',
        CLAWD_SUBPET_SPRITES: 'readonly',
        CLAWD_SUBPET_CELL: 'readonly',
        CLAWD_IDLE_VARIATIONS: 'readonly',
        CLAWD_KEYBOARD_SHORTCUTS: 'readonly',
        CLAWD_PAGE_CONTEXTS: 'readonly',
        CLAWD_DOM_CLEANUP_SELECTORS: 'readonly',
        CLAWD_RUNTIME_ACTIONS: 'readonly',
        CLAWD_PORT_MSG_TYPES: 'readonly',
        CLAWD_DOWNSTREAM_PORT_MSG_TYPES: 'readonly',
        CLAWD_TRAVEL_FREQS: 'readonly',
        CLAWD_START_CORNERS: 'readonly',
        CLAWD_NAME_TAG_THEMES: 'readonly',
        CLAWD_SETTING_KEYS: 'readonly',
        CLAWD_CONFIG_KEYS: 'readonly',
        clawdDefaultState: 'readonly',
        clawdMigrateState: 'readonly',
        clawdSanitizePlainText: 'readonly',
        clawdSanitizeHostname: 'readonly',
        clawdSanitizeConfigValue: 'readonly',
        clawdSanitizeSettingValue: 'readonly',
        clawdIsHexColor: 'readonly',
        clawdAssignPlain: 'readonly',
        clawdPlainMerge: 'readonly',
        clawdValidateRuntimeMessage: 'readonly',
        clawdValidatePortMessage: 'readonly',
        clawdHasExtensionContext: 'readonly',
        clawdIsExtensionContextError: 'readonly',
        clawdSafeExtensionCall: 'readonly',
        clawdGuardExtensionCallback: 'readonly',
        clawdLevelFromXp: 'readonly',
        clawdXpForLevel: 'readonly',
        clawdISOWeek: 'readonly',
        clawdDailyQuestForDate: 'readonly',
        clawdWeeklyChallengeForWeek: 'readonly',
        clawdEnsureWeeklyChallenge: 'readonly',
        clawdEnsureDailyQuest: 'readonly',
        clawdRegisterDailyProgress: 'readonly',
        clawdRegisterWeeklyProgress: 'readonly',
        clawdEffectiveAccessories: 'readonly',
        clawdHostIsBlocked: 'readonly',
        clawdSubPetImageUrl: 'readonly',
        clawdSubPetBounds: 'readonly',
        clawdPageContextFromHost: 'readonly'
      }
    },
    rules: {
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-caller': 'error',
      'no-extend-native': 'warn',
      'no-global-assign': 'error',
      'no-implicit-eval': 'error',
      'no-labels': 'error',
      'no-proto': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'eqeqeq': ['warn', 'smart'],
      'no-case-declarations': 'warn',
      'no-unused-vars': ['warn', { 'args': 'none', 'varsIgnorePattern': '^_' }],
      'no-redeclare': 'error',
      'no-shadow-restricted-names': 'error',
      'no-use-before-define': ['warn', { 'functions': false, 'classes': false }]
    }
  },
  {
    ignores: ['docs/', 'tests/tools/', 'tests/_shots/', 'tests/sprite-out/']
  }
];
